/* Generated from runtime_template.c by gen_runtime.py. Do not edit directly. */
#include "runtime.h"

const char *DINO_RUNTIME_C =
    "#define _POSIX_C_SOURCE 200809L\n"
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include <stdbool.h>\n"
    "#include <stdarg.h>\n"
    "#include <unistd.h>\n"
    "#include <time.h>\n"
    "#include <setjmp.h>\n"
    "\n"
    "/* ── Dino dynamic value runtime ────────────────────────────────────────────\n"
    "   Every Dino value is a DinoValue: a tagged union that can hold null, a bool,\n"
    "   an integer, a float, a string, an array or a dictionary. Arrays and\n"
    "   dictionaries are reference types and can hold mixed values and grow. */\n"
    "\n"
    "typedef enum { DINO_NULL, DINO_BOOL, DINO_INT, DINO_FLOAT, DINO_STRING, DINO_ARRAY, DINO_DICT } DinoType;\n"
    "\n"
    "typedef struct DinoValue DinoValue;\n"
    "typedef struct DinoArray DinoArray;\n"
    "typedef struct DinoDict DinoDict;\n"
    "\n"
    "struct DinoArray { size_t len; size_t cap; DinoValue *items; };\n"
    "struct DinoDict { size_t len; size_t cap; DinoValue *keys; DinoValue *vals; };\n"
    "struct DinoValue {\n"
    "    DinoType type;\n"
    "    union {\n"
    "        long long i;\n"
    "        double f;\n"
    "        int b;\n"
    "        const char *s;\n"
    "        DinoArray *arr;\n"
    "        DinoDict *dict;\n"
    "    } as;\n"
    "};\n"
    "\n"
    "static DinoValue _dino_null(void);\n"
    "static DinoValue _dino_bool(int b);\n"
    "static DinoValue _dino_int(long long i);\n"
    "static DinoValue _dino_float(double f);\n"
    "static DinoValue _dino_str(const char *s);\n"
    "static const char *_dino_cstr(DinoValue v);\n"
    "static int _dino_equals(DinoValue a, DinoValue b);\n"
    "static void _dino_throw(DinoValue v) __attribute__((noreturn));\n"
    "\n"
    "/* Rotating buffers so that several values can be rendered in one expression. */\n"
    "#define _DINO_POOL 16\n"
    "static char _dino_pool[_DINO_POOL][1024];\n"
    "static int _dino_pool_idx = 0;\n"
    "static char *_dino_pool_next(void) {\n"
    "    char *b = _dino_pool[_dino_pool_idx];\n"
    "    _dino_pool_idx = (_dino_pool_idx + 1) % _DINO_POOL;\n"
    "    b[0] = '\\0';\n"
    "    return b;\n"
    "}\n"
    "\n"
    "static void _dino_render(char *dst, size_t cap, DinoValue v) {\n"
    "    size_t len = strlen(dst);\n"
    "    size_t rem = cap > len ? cap - len : 0;\n"
    "    char *p = dst + len;\n"
    "    switch (v.type) {\n"
    "        case DINO_NULL: snprintf(p, rem, \"null\"); break;\n"
    "        case DINO_BOOL: snprintf(p, rem, \"%s\", v.as.b ? \"true\" : \"false\"); break;\n"
    "        case DINO_INT: snprintf(p, rem, \"%lld\", v.as.i); break;\n"
    "        case DINO_FLOAT: snprintf(p, rem, \"%g\", v.as.f); break;\n"
    "        case DINO_STRING: snprintf(p, rem, \"%s\", v.as.s ? v.as.s : \"\"); break;\n"
    "        case DINO_ARRAY:\n"
    "            snprintf(p, rem, \"[\");\n"
    "            for (size_t i = 0; i < v.as.arr->len; i++) {\n"
    "                if (i) { len = strlen(dst); snprintf(dst + len, cap > len ? cap - len : 0, \", \"); }\n"
    "                _dino_render(dst, cap, v.as.arr->items[i]);\n"
    "            }\n"
    "            len = strlen(dst); snprintf(dst + len, cap > len ? cap - len : 0, \"]\");\n"
    "            break;\n"
    "        case DINO_DICT:\n"
    "            snprintf(p, rem, \"{\");\n"
    "            for (size_t i = 0; i < v.as.dict->len; i++) {\n"
    "                if (i) { len = strlen(dst); snprintf(dst + len, cap > len ? cap - len : 0, \", \"); }\n"
    "                _dino_render(dst, cap, v.as.dict->keys[i]);\n"
    "                len = strlen(dst); snprintf(dst + len, cap > len ? cap - len : 0, \": \");\n"
    "                _dino_render(dst, cap, v.as.dict->vals[i]);\n"
    "            }\n"
    "            len = strlen(dst); snprintf(dst + len, cap > len ? cap - len : 0, \"}\");\n"
    "            break;\n"
    "    }\n"
    "}\n"
    "\n"
    "static const char *_dino_cstr(DinoValue v) {\n"
    "    if (v.type == DINO_STRING) return v.as.s ? v.as.s : \"\";\n"
    "    char *b = _dino_pool_next();\n"
    "    _dino_render(b, 1024, v);\n"
    "    return b;\n"
    "}\n"
    "\n"
    "static DinoValue _dino_null(void) { DinoValue v; memset(&v, 0, sizeof v); v.type = DINO_NULL; return v; }\n"
    "static DinoValue _dino_bool(int b) { DinoValue v; memset(&v, 0, sizeof v); v.type = DINO_BOOL; v.as.b = b ? 1 : 0; return v; }\n"
    "static DinoValue _dino_int(long long i) { DinoValue v; memset(&v, 0, sizeof v); v.type = DINO_INT; v.as.i = i; return v; }\n"
    "static DinoValue _dino_float(double f) { DinoValue v; memset(&v, 0, sizeof v); v.type = DINO_FLOAT; v.as.f = f; return v; }\n"
    "static DinoValue _dino_str(const char *s) { DinoValue v; memset(&v, 0, sizeof v); v.type = DINO_STRING; v.as.s = s ? s : \"\"; return v; }\n"
    "\n"
    "static int _dino_is_num(DinoValue v) { return v.type == DINO_INT || v.type == DINO_FLOAT || v.type == DINO_BOOL; }\n"
    "\n"
    "static double _dino_to_double(DinoValue v) {\n"
    "    switch (v.type) {\n"
    "        case DINO_INT: return (double)v.as.i;\n"
    "        case DINO_FLOAT: return v.as.f;\n"
    "        case DINO_BOOL: return (double)v.as.b;\n"
    "        case DINO_STRING: return atof(v.as.s ? v.as.s : \"\");\n"
    "        default: return 0.0;\n"
    "    }\n"
    "}\n"
    "\n"
    "static long long _dino_to_int(DinoValue v) {\n"
    "    switch (v.type) {\n"
    "        case DINO_INT: return v.as.i;\n"
    "        case DINO_FLOAT: return (long long)v.as.f;\n"
    "        case DINO_BOOL: return v.as.b;\n"
    "        case DINO_STRING: return atoll(v.as.s ? v.as.s : \"\");\n"
    "        default: return 0;\n"
    "    }\n"
    "}\n"
    "\n"
    "static int _dino_truthy(DinoValue v) {\n"
    "    switch (v.type) {\n"
    "        case DINO_NULL: return 0;\n"
    "        case DINO_BOOL: return v.as.b;\n"
    "        case DINO_INT: return v.as.i != 0;\n"
    "        case DINO_FLOAT: return v.as.f != 0.0;\n"
    "        case DINO_STRING: return v.as.s && v.as.s[0];\n"
    "        default: return 1;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ── try / catch / throw ──────────────────────────────────────────────────── */\n"
    "\n"
    "typedef struct DinoTryFrame { jmp_buf buf; DinoValue err; struct DinoTryFrame *prev; } DinoTryFrame;\n"
    "static DinoTryFrame *_dino_try_top = NULL;\n"
    "\n"
    "static void _dino_throw(DinoValue v) {\n"
    "    if (_dino_try_top) { _dino_try_top->err = v; longjmp(_dino_try_top->buf, 1); }\n"
    "    fprintf(stderr, \"Uncaught error: %s\\n\", _dino_cstr(v));\n"
    "    exit(1);\n"
    "}\n"
    "\n"
    "/* ── Comparison / logic ───────────────────────────────────────────────────── */\n"
    "\n"
    "static int _dino_equals(DinoValue a, DinoValue b) {\n"
    "    if (a.type == DINO_STRING && b.type == DINO_STRING)\n"
    "        return strcmp(a.as.s ? a.as.s : \"\", b.as.s ? b.as.s : \"\") == 0;\n"
    "    if (_dino_is_num(a) && _dino_is_num(b)) return _dino_to_double(a) == _dino_to_double(b);\n"
    "    if (a.type != b.type) return 0;\n"
    "    switch (a.type) {\n"
    "        case DINO_NULL: return 1;\n"
    "        case DINO_ARRAY: return a.as.arr == b.as.arr;\n"
    "        case DINO_DICT: return a.as.dict == b.as.dict;\n"
    "        default: return 1;\n"
    "    }\n"
    "}\n"
    "\n"
    "static int _dino_cmp(DinoValue a, DinoValue b) {\n"
    "    if (a.type == DINO_STRING && b.type == DINO_STRING) {\n"
    "        int c = strcmp(a.as.s ? a.as.s : \"\", b.as.s ? b.as.s : \"\");\n"
    "        return c < 0 ? -1 : (c > 0 ? 1 : 0);\n"
    "    }\n"
    "    double x = _dino_to_double(a), y = _dino_to_double(b);\n"
    "    return x < y ? -1 : (x > y ? 1 : 0);\n"
    "}\n"
    "\n"
    "static DinoValue _dino_eq(DinoValue a, DinoValue b) { return _dino_bool(_dino_equals(a, b)); }\n"
    "static DinoValue _dino_ne(DinoValue a, DinoValue b) { return _dino_bool(!_dino_equals(a, b)); }\n"
    "static DinoValue _dino_lt(DinoValue a, DinoValue b) { return _dino_bool(_dino_cmp(a, b) < 0); }\n"
    "static DinoValue _dino_le(DinoValue a, DinoValue b) { return _dino_bool(_dino_cmp(a, b) <= 0); }\n"
    "static DinoValue _dino_gt(DinoValue a, DinoValue b) { return _dino_bool(_dino_cmp(a, b) > 0); }\n"
    "static DinoValue _dino_ge(DinoValue a, DinoValue b) { return _dino_bool(_dino_cmp(a, b) >= 0); }\n"
    "static DinoValue _dino_not(DinoValue a) { return _dino_bool(!_dino_truthy(a)); }\n"
    "static DinoValue _dino_and(DinoValue a, DinoValue b) { return _dino_bool(_dino_truthy(a) && _dino_truthy(b)); }\n"
    "static DinoValue _dino_or(DinoValue a, DinoValue b) { return _dino_bool(_dino_truthy(a) || _dino_truthy(b)); }\n"
    "\n"
    "static DinoValue _dino_neg(DinoValue a) {\n"
    "    if (a.type == DINO_FLOAT) return _dino_float(-a.as.f);\n"
    "    return _dino_int(-_dino_to_int(a));\n"
    "}\n"
    "\n"
    "static DinoValue _dino_inc(DinoValue *v) {\n"
    "    if (v->type == DINO_FLOAT) { v->as.f += 1.0; return *v; }\n"
    "    long long n = _dino_to_int(*v) + 1;\n"
    "    v->type = DINO_INT; v->as.i = n;\n"
    "    return *v;\n"
    "}\n"
    "\n"
    "static DinoValue _dino_dec(DinoValue *v) {\n"
    "    if (v->type == DINO_FLOAT) { v->as.f -= 1.0; return *v; }\n"
    "    long long n = _dino_to_int(*v) - 1;\n"
    "    v->type = DINO_INT; v->as.i = n;\n"
    "    return *v;\n"
    "}\n"
    "\n"
    "/* ── Arithmetic ───────────────────────────────────────────────────────────── */\n"
    "\n"
    "static DinoValue _dino_add(DinoValue a, DinoValue b) {\n"
    "    if (a.type == DINO_STRING || b.type == DINO_STRING) {\n"
    "        const char *sa = _dino_cstr(a);\n"
    "        const char *sb = _dino_cstr(b);\n"
    "        size_t n = strlen(sa) + strlen(sb) + 1;\n"
    "        char *r = malloc(n);\n"
    "        strcpy(r, sa);\n"
    "        strcat(r, sb);\n"
    "        return _dino_str(r);\n"
    "    }\n"
    "    if (a.type == DINO_FLOAT || b.type == DINO_FLOAT)\n"
    "        return _dino_float(_dino_to_double(a) + _dino_to_double(b));\n"
    "    return _dino_int(_dino_to_int(a) + _dino_to_int(b));\n"
    "}\n"
    "\n"
    "static DinoValue _dino_sub(DinoValue a, DinoValue b) {\n"
    "    if (a.type == DINO_FLOAT || b.type == DINO_FLOAT)\n"
    "        return _dino_float(_dino_to_double(a) - _dino_to_double(b));\n"
    "    return _dino_int(_dino_to_int(a) - _dino_to_int(b));\n"
    "}\n"
    "\n"
    "static DinoValue _dino_mul(DinoValue a, DinoValue b) {\n"
    "    if (a.type == DINO_FLOAT || b.type == DINO_FLOAT)\n"
    "        return _dino_float(_dino_to_double(a) * _dino_to_double(b));\n"
    "    return _dino_int(_dino_to_int(a) * _dino_to_int(b));\n"
    "}\n"
    "\n"
    "static DinoValue _dino_div(DinoValue a, DinoValue b) {\n"
    "    double d = _dino_to_double(b);\n"
    "    if (d == 0.0) _dino_throw(_dino_str(\"division by zero\"));\n"
    "    if (a.type == DINO_FLOAT || b.type == DINO_FLOAT) return _dino_float(_dino_to_double(a) / d);\n"
    "    return _dino_int(_dino_to_int(a) / (long long)d);\n"
    "}\n"
    "\n"
    "static DinoValue _dino_mod(DinoValue a, DinoValue b) {\n"
    "    long long d = _dino_to_int(b);\n"
    "    if (d == 0) _dino_throw(_dino_str(\"modulo by zero\"));\n"
    "    return _dino_int(_dino_to_int(a) % d);\n"
    "}\n"
    "\n"
    "/* ── Arrays ───────────────────────────────────────────────────────────────── */\n"
    "\n"
    "static DinoArray *_dino_array_new(void) {\n"
    "    DinoArray *a = malloc(sizeof(DinoArray));\n"
    "    a->len = 0;\n"
    "    a->cap = 4;\n"
    "    a->items = malloc(sizeof(DinoValue) * a->cap);\n"
    "    return a;\n"
    "}\n"
    "\n"
    "static void _dino_array_push(DinoArray *a, DinoValue v) {\n"
    "    if (a->len == a->cap) {\n"
    "        a->cap *= 2;\n"
    "        a->items = realloc(a->items, sizeof(DinoValue) * a->cap);\n"
    "    }\n"
    "    a->items[a->len++] = v;\n"
    "}\n"
    "\n"
    "static DinoValue _dino_array_from(size_t n, DinoValue *items) {\n"
    "    DinoArray *a = _dino_array_new();\n"
    "    for (size_t i = 0; i < n; i++) _dino_array_push(a, items[i]);\n"
    "    DinoValue v = _dino_null();\n"
    "    v.type = DINO_ARRAY;\n"
    "    v.as.arr = a;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/* ── Dictionaries ─────────────────────────────────────────────────────────── */\n"
    "\n"
    "static DinoDict *_dino_dict_new(void) {\n"
    "    DinoDict *d = malloc(sizeof(DinoDict));\n"
    "    d->len = 0;\n"
    "    d->cap = 4;\n"
    "    d->keys = malloc(sizeof(DinoValue) * d->cap);\n"
    "    d->vals = malloc(sizeof(DinoValue) * d->cap);\n"
    "    return d;\n"
    "}\n"
    "\n"
    "static long long _dino_dict_find(DinoDict *d, DinoValue key) {\n"
    "    for (size_t i = 0; i < d->len; i++) if (_dino_equals(d->keys[i], key)) return (long long)i;\n"
    "    return -1;\n"
    "}\n"
    "\n"
    "static void _dino_dict_put(DinoDict *d, DinoValue key, DinoValue val) {\n"
    "    long long i = _dino_dict_find(d, key);\n"
    "    if (i >= 0) { d->vals[i] = val; return; }\n"
    "    if (d->len == d->cap) {\n"
    "        d->cap *= 2;\n"
    "        d->keys = realloc(d->keys, sizeof(DinoValue) * d->cap);\n"
    "        d->vals = realloc(d->vals, sizeof(DinoValue) * d->cap);\n"
    "    }\n"
    "    d->keys[d->len] = key;\n"
    "    d->vals[d->len] = val;\n"
    "    d->len++;\n"
    "}\n"
    "\n"
    "static DinoValue _dino_dict_get(DinoDict *d, DinoValue key) {\n"
    "    long long i = _dino_dict_find(d, key);\n"
    "    return i >= 0 ? d->vals[i] : _dino_null();\n"
    "}\n"
    "\n"
    "static DinoValue _dino_dict_from(size_t n, DinoValue *kv) {\n"
    "    DinoDict *d = _dino_dict_new();\n"
    "    for (size_t i = 0; i < n; i++) _dino_dict_put(d, kv[2 * i], kv[2 * i + 1]);\n"
    "    DinoValue v = _dino_null();\n"
    "    v.type = DINO_DICT;\n"
    "    v.as.dict = d;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/* ── Indexing / length / list helpers ─────────────────────────────────────── */\n"
    "\n"
    "static DinoValue _dino_get(DinoValue obj, DinoValue key) {\n"
    "    if (obj.type == DINO_ARRAY) {\n"
    "        // A non-numeric key searches for a matching value and returns its\n"
    "        // index (or null). Numeric keys index the array.\n"
    "        if (key.type != DINO_INT && key.type != DINO_FLOAT && key.type != DINO_BOOL) {\n"
    "            for (size_t i = 0; i < obj.as.arr->len; i++)\n"
    "                if (_dino_equals(obj.as.arr->items[i], key)) return _dino_int((long long)i);\n"
    "            return _dino_null();\n"
    "        }\n"
    "        long long i = _dino_to_int(key);\n"
    "        if (i < 0) i += (long long)obj.as.arr->len;\n"
    "        if (i < 0 || (size_t)i >= obj.as.arr->len) _dino_throw(_dino_str(\"array index out of range\"));\n"
    "        return obj.as.arr->items[i];\n"
    "    }\n"
    "    if (obj.type == DINO_DICT) {\n"
    "        long long idx = _dino_dict_find(obj.as.dict, key);\n"
    "        if (idx >= 0) return obj.as.dict->vals[idx];\n"
    "        // Positional fallback: an integer key that is not a stored key refers\n"
    "        // to the nth entry (0-based, negatives from the end).\n"
    "        if (key.type == DINO_INT || key.type == DINO_FLOAT || key.type == DINO_BOOL) {\n"
    "            long long i = _dino_to_int(key);\n"
    "            if (i < 0) i += (long long)obj.as.dict->len;\n"
    "            if (i >= 0 && (size_t)i < obj.as.dict->len) return obj.as.dict->vals[i];\n"
    "        }\n"
    "        return _dino_null();\n"
    "    }\n"
    "    if (obj.type == DINO_STRING) {\n"
    "        if (key.type != DINO_INT && key.type != DINO_FLOAT && key.type != DINO_BOOL) return _dino_null();\n"
    "        long long i = _dino_to_int(key);\n"
    "        const char *s = obj.as.s ? obj.as.s : \"\";\n"
    "        size_t len = strlen(s);\n"
    "        if (i < 0) i += (long long)len;\n"
    "        if (i < 0 || (size_t)i >= len) _dino_throw(_dino_str(\"string index out of range\"));\n"
    "        char *buf = _dino_pool_next();\n"
    "        buf[0] = s[i];\n"
    "        buf[1] = '\\0';\n"
    "        return _dino_str(buf);\n"
    "    }\n"
    "    return _dino_null();\n"
    "}\n"
    "\n"
    "/* Reverse dictionary lookup: the key whose stored value equals `val`.\n"
    " * Falls back to positional access for a bare integer, so `d.key[n]` still\n"
    " * selects the nth key when no value matches. Returns null when not found. */\n"
    "static DinoValue _dino_key_of_value(DinoValue obj, DinoValue val) {\n"
    "    if (obj.type != DINO_DICT) return _dino_null();\n"
    "    for (size_t i = 0; i < obj.as.dict->len; i++)\n"
    "        if (_dino_equals(obj.as.dict->vals[i], val)) return obj.as.dict->keys[i];\n"
    "    if (val.type == DINO_INT || val.type == DINO_FLOAT || val.type == DINO_BOOL) {\n"
    "        long long i = _dino_to_int(val);\n"
    "        if (i < 0) i += (long long)obj.as.dict->len;\n"
    "        if (i >= 0 && (size_t)i < obj.as.dict->len) return obj.as.dict->keys[i];\n"
    "    }\n"
    "    return _dino_null();\n"
    "}\n"
    "\n"
    "static void _dino_set(DinoValue obj, DinoValue key, DinoValue val) {\n"
    "    if (obj.type == DINO_ARRAY) {\n"
    "        long long i = _dino_to_int(key);\n"
    "        if (i < 0) i += (long long)obj.as.arr->len;\n"
    "        if (i < 0 || (size_t)i >= obj.as.arr->len) _dino_throw(_dino_str(\"array index out of range\"));\n"
    "        obj.as.arr->items[i] = val;\n"
    "    } else if (obj.type == DINO_DICT) {\n"
    "        _dino_dict_put(obj.as.dict, key, val);\n"
    "    } else {\n"
    "        _dino_throw(_dino_str(\"cannot assign to an index of this value\"));\n"
    "    }\n"
    "}\n"
    "\n"
    "/* `delete arr[i]` / `delete dict[k]`: remove an entry in place and return the\n"
    " * removed value. A numeric key indexes an array (negatives from the end, and\n"
    " * out of range throws like an out-of-range read); a non-numeric key removes\n"
    " * the first array element equal to it, or the dictionary entry with that key.\n"
    " * Nothing deleted yields null. */\n"
    "static DinoValue _dino_remove(DinoValue obj, DinoValue key) {\n"
    "    if (obj.type == DINO_ARRAY) {\n"
    "        DinoArray *a = obj.as.arr;\n"
    "        long long i;\n"
    "        if (_dino_is_num(key)) {\n"
    "            i = _dino_to_int(key);\n"
    "            if (i < 0) i += (long long)a->len;\n"
    "            if (i < 0 || (size_t)i >= a->len) _dino_throw(_dino_str(\"array index out of range\"));\n"
    "        } else {\n"
    "            i = -1;\n"
    "            for (size_t j = 0; j < a->len; j++) {\n"
    "                if (_dino_equals(a->items[j], key)) { i = (long long)j; break; }\n"
    "            }\n"
    "            if (i < 0) return _dino_null();\n"
    "        }\n"
    "        DinoValue removed = a->items[i];\n"
    "        memmove(&a->items[i], &a->items[i + 1], sizeof(DinoValue) * (a->len - (size_t)i - 1));\n"
    "        a->len--;\n"
    "        return removed;\n"
    "    }\n"
    "    if (obj.type == DINO_DICT) {\n"
    "        DinoDict *d = obj.as.dict;\n"
    "        long long i = _dino_dict_find(d, key);\n"
    "        // A numeric key that is not a stored key falls back to the nth entry\n"
    "        // (0-based, negatives from the end), matching dict indexing reads.\n"
    "        if (i < 0 && _dino_is_num(key)) {\n"
    "            i = _dino_to_int(key);\n"
    "            if (i < 0) i += (long long)d->len;\n"
    "            if (i < 0 || (size_t)i >= d->len) return _dino_null();\n"
    "        }\n"
    "        if (i < 0) return _dino_null();\n"
    "        DinoValue removed = d->vals[i];\n"
    "        memmove(&d->keys[i], &d->keys[i + 1], sizeof(DinoValue) * (d->len - (size_t)i - 1));\n"
    "        memmove(&d->vals[i], &d->vals[i + 1], sizeof(DinoValue) * (d->len - (size_t)i - 1));\n"
    "        d->len--;\n"
    "        return removed;\n"
    "    }\n"
    "    _dino_throw(_dino_str(\"cannot delete from this value\"));\n"
    "    return _dino_null();\n"
    "}\n"
    "\n"
    "static DinoValue _dino_len(DinoValue v) {\n"
    "    if (v.type == DINO_STRING) return _dino_int((long long)strlen(v.as.s ? v.as.s : \"\"));\n"
    "    if (v.type == DINO_ARRAY) return _dino_int((long long)v.as.arr->len);\n"
    "    if (v.type == DINO_DICT) return _dino_int((long long)v.as.dict->len);\n"
    "    return _dino_int(0);\n"
    "}\n"
    "\n"
    "static DinoValue _dino_push(DinoValue arr, DinoValue v) {\n"
    "    if (arr.type == DINO_ARRAY) _dino_array_push(arr.as.arr, v);\n"
    "    return arr;\n"
    "}\n"
    "\n"
    "static DinoValue _dino_pop(DinoValue arr) {\n"
    "    if (arr.type == DINO_ARRAY && arr.as.arr->len > 0) return arr.as.arr->items[--arr.as.arr->len];\n"
    "    return _dino_null();\n"
    "}\n"
    "\n"
    "static DinoValue _dino_has(DinoValue obj, DinoValue key) {\n"
    "    if (obj.type == DINO_DICT) return _dino_bool(_dino_dict_find(obj.as.dict, key) >= 0);\n"
    "    if (obj.type == DINO_ARRAY) {\n"
    "        for (size_t i = 0; i < obj.as.arr->len; i++)\n"
    "            if (_dino_equals(obj.as.arr->items[i], key)) return _dino_bool(1);\n"
    "    }\n"
    "    return _dino_bool(0);\n"
    "}\n"
    "\n"
    "static DinoValue _dino_keys(DinoValue obj) {\n"
    "    if (obj.type != DINO_DICT) return _dino_array_from(0, NULL);\n"
    "    DinoArray *a = _dino_array_new();\n"
    "    for (size_t i = 0; i < obj.as.dict->len; i++) _dino_array_push(a, obj.as.dict->keys[i]);\n"
    "    DinoValue v = _dino_null();\n"
    "    v.type = DINO_ARRAY;\n"
    "    v.as.arr = a;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "static DinoValue _dino_values(DinoValue obj) {\n"
    "    if (obj.type != DINO_DICT) return _dino_array_from(0, NULL);\n"
    "    DinoArray *a = _dino_array_new();\n"
    "    for (size_t i = 0; i < obj.as.dict->len; i++) _dino_array_push(a, obj.as.dict->vals[i]);\n"
    "    DinoValue v = _dino_null();\n"
    "    v.type = DINO_ARRAY;\n"
    "    v.as.arr = a;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/* `arr.minimized`: a NEW array with duplicate elements removed. The first\n"
    " * occurrence of each element wins, so the original order is preserved and the\n"
    " * input array is left untouched. Non-arrays yield an empty array. */\n"
    "static DinoValue _dino_minimize(DinoValue obj) {\n"
    "    if (obj.type != DINO_ARRAY) return _dino_array_from(0, NULL);\n"
    "    DinoArray *src = obj.as.arr;\n"
    "    DinoArray *a = _dino_array_new();\n"
    "    for (size_t i = 0; i < src->len; i++) {\n"
    "        bool seen = false;\n"
    "        for (size_t j = 0; j < a->len; j++) {\n"
    "            if (_dino_equals(a->items[j], src->items[i])) { seen = true; break; }\n"
    "        }\n"
    "        if (!seen) _dino_array_push(a, src->items[i]);\n"
    "    }\n"
    "    DinoValue v = _dino_null();\n"
    "    v.type = DINO_ARRAY;\n"
    "    v.as.arr = a;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/* ── Output / input / timing ──────────────────────────────────────────────── */\n"
    "\n"
    "static void _dino_printv(size_t n, DinoValue *vals) {\n"
    "    for (size_t i = 0; i < n; i++) {\n"
    "        if (i) fputc(' ', stdout);\n"
    "        fputs(_dino_cstr(vals[i]), stdout);\n"
    "    }\n"
    "    fputc('\\n', stdout);\n"
    "}\n"
    "\n"
    "static void _dino_eprintv(const char *color, size_t n, DinoValue *vals) {\n"
    "    int tty = color && !getenv(\"NO_COLOR\") && isatty(fileno(stderr));\n"
    "    if (tty) fputs(color, stderr);\n"
    "    for (size_t i = 0; i < n; i++) {\n"
    "        if (i) fputc(' ', stderr);\n"
    "        fputs(_dino_cstr(vals[i]), stderr);\n"
    "    }\n"
    "    fputc('\\n', stderr);\n"
    "    if (tty) fputs(\"\\033[0m\", stderr);\n"
    "}\n"
    "\n"
    "static DinoValue _dino_fmt(const char *fmt, ...) {\n"
    "    va_list ap, ap2;\n"
    "    va_start(ap, fmt);\n"
    "    va_copy(ap2, ap);\n"
    "    int n = vsnprintf(NULL, 0, fmt, ap);\n"
    "    va_end(ap);\n"
    "    if (n < 0) n = 0;\n"
    "    char *buf = malloc((size_t)n + 1);\n"
    "    vsnprintf(buf, (size_t)n + 1, fmt, ap2);\n"
    "    va_end(ap2);\n"
    "    return _dino_str(buf);\n"
    "}\n"
    "\n"
    "static void _dino_delay(double seconds) {\n"
    "    struct timespec ts;\n"
    "    ts.tv_sec = (time_t)seconds;\n"
    "    ts.tv_nsec = (long)((seconds - (double)ts.tv_sec) * 1000000000.0);\n"
    "    nanosleep(&ts, NULL);\n"
    "}\n"
    "\n"
    "static DinoValue _dino_input(DinoValue prompt) {\n"
    "    const char *p = _dino_cstr(prompt);\n"
    "    if (p && p[0]) { fputs(p, stdout); fflush(stdout); }\n"
    "    char *line = NULL;\n"
    "    size_t cap = 0;\n"
    "    ssize_t n = getline(&line, &cap, stdin);\n"
    "    if (n < 0) { free(line); return _dino_str(\"\"); }\n"
    "    while (n > 0 && (line[n - 1] == '\\n' || line[n - 1] == '\\r')) line[--n] = '\\0';\n"
    "    return _dino_str(line);\n"
    "}\n"
    ;
